### ISSUE TITLE
Error al cerrar la aplicación

### ISSUE THREAD

**Issue by javics2002** [javics2002/VDM#26]
Al cerrar la aplicación:

FATAL EXCEPTION: Thread-10
Process: com.example.PR2, PID: 5941
java.lang.NullPointerException: Attempt to invoke virtual method 'void [android](https://cvdof.ucm.es/moodle/mod/resource/view.php?id=302550).graphics.Canvas.drawColor(int)' on a null object reference
    at com.example.libengineandroid.GraphicsAndroid.clear(GraphicsAndroid.java:69)
    at com.example.logiclib.InitialScene.render(InitialScene.java:96)
    at com.example.libengineandroid.EngineAndroid.render(EngineAndroid.java:114)
    at com.example.libengineandroid.EngineAndroid.run(EngineAndroid.java:107)
    at java.lang.Thread.run(Thread.java:1012)

**Comment by druiz07** [comment]
El unico error expermientado tratando de reproducir el error cerrando la aplicacion desde distintos sitios es este:
[SurfaceView[com.example.PR2/com.example.p1.MainActivity]#1(BLAST Consumer)1](id:669900000001,api:0,p:-1,c:26265) disconnect: not connected (req=2)
No tiene nada que ver pero si lo conseguimos solucionar estaria criminal

**Comment by josemiguelvdz** [comment]
Dada la descripción del error de Toni, se ha implementado código defensivo al clear() 

![image](https://github.com/javics2002/VDM/assets/75903737/ee8d055c-280b-4c92-8864-a3f2050125ca)

(No se ha podido replicar)
