### ISSUE TITLE
Ruta de producto de la tienda inválida

### ISSUE THREAD

**Issue by javics2002** [javics2002/VDM#27]
No usáis el hash para comprobar modificaciones en el guardado, haciendo cambios, según qué modificación se lleve a cabo, la aplicación crashea (me ha pasado con la tienda) y en ese caso, la aplicación ya no se recupera.

FATAL EXCEPTION: Thread-6
Process: com.example.PR2, PID: 7013
java.lang.NullPointerException: Attempt to invoke virtual method '[android](https://cvdof.ucm.es/moodle/mod/resource/view.php?id=302550).graphics.Bitmap com.example.libengineandroid.ImageAndroid.getImage()' on a null object reference
    at com.example.libengineandroid.GraphicsAndroid.drawImage(GraphicsAndroid.java:135)
    at com.example.logiclib.CustomBackground.render(CustomBackground.java:78)
    at com.example.logiclib.ShopScene.render(ShopScene.java:283)
    at com.example.libengineandroid.EngineAndroid.render(EngineAndroid.java:114)
    at com.example.libengineandroid.EngineAndroid.run(EngineAndroid.java:107)
    at java.lang.Thread.run(Thread.java:923)

**Comment by javics2002** [comment]
Ahora actualizo el contenido de los productos de la tienda. La excepción se produce al introducir una ruta de imagen inexistente. Este problema pasaría con cualquier imagen inexistente que se quiera dibujar.
Al menos, ahora la aplicación se podría recuperar volviendo a poner la ruta correctamente o borrando el producto.

En este caso concreto, se podría mejorar eliminando directamente un producto corrupto de la tienda, pero tendría la desventaja de no tener feedback de que has puesto un producto mal.
